### PR TITLE
fix: highlight color

### PR DESCRIPTION
**Pull request by bonswouar**
define the color of the progress bar

Before:
dunst_before

After:
dunst_after

### CODE REVIEW

**Review by sgoudham — CHANGES_REQUESTED** [review]
Thanks for the PR!

Sorry that it's not documented but this repository uses https://github.com/catppuccin/whiskers to generate the 4 theme files. 

Please edit the [dunst.tera](https://github.com/catppuccin/dunst/blob/main/dunst.tera) file, run whiskers and then commit your changes. 

Feel free to ask if you have any questions around whiskers setup or around editing the file!

**Comment by bonswouar** [comment]
Alright I've set it to `palette.text` (let me know if there is a better palette color to use) and re-generated with whiskers

**Comment by sgoudham** [comment]
Thanks for updating it via whiskers!

It seems like the default is `blue` from your screenshot but I think `text` looks quite nice there. I think I know how Latte looks in my mind but if you'll indulge me, could you please send a screenshot of what Latte looks like with the new progress bar?

**Comment by bonswouar** [comment]
Here is how it looks with latte:
dunst_latte

**Comment by sgoudham** [comment]
Hmmm, it feels quite odd with the `blue` border but `text` fill.

If you'll indulge me once again, could you please show me how it looks with the entire progress bar as `blue` for both mocha (or another dark flavour) and latte?

**Comment by bonswouar** [comment]
No worry I don't mind, you probably have a better eye than me for that ;)

Latte:
dunst_latte
Frappe:
dunst_frappe
Mocha:
dunst_mocha
Macchiato:
dunst_macchiatto

**Comment by sgoudham** [comment]
I think the blue looks quite good!

Happy to approve and merge this PR if the whiskers template is updated to use `palette.blue.hex` and the other files are updated as per the template.

**Review by sgoudham — APPROVED** [review]
Thanks again for the PR!

**Pull request merged**
